In [3]:
import pandas as pd

In [22]:
data = pd.read_csv("data/data extraction/ALA_SER/ALA_SER_FUS_sequential.csv")
data

,WT,Unnamed: 1,-4S+4A,Unnamed: 3,-4A+4S,Unnamed: 5,Critical Temperature,Unnamed: 7
0,X,Y,X,Y,X,Y,X,Y
1,0.004005240870900095,319.97304582210245,0.0003966171125484863,315.1212938005391,0.0010754046086513813,289.89218328840974,0.149717237650606,344.07008086253376
2,0.012302234079078739,324.9865229110512,0.024113136511269034,330.00000000000006,0.000005130370610062496,295.067385444744,0.15663771295971077,338.5714285714286
3,0.04060609409099697,334.85175202156336,0.07223127710710239,334.85175202156336,0.00010300205609467539,300.08086253369277,0.15548535279190814,339.5417789757413
4,0.012400105764563352,330.00000000000006,0.0957552102859984,339.86522911051213,0.00019771659043460454,304.9326145552561,NaN,NaN
5,0.05944481497121068,339.86522911051213,0.25856633766520776,339.86522911051213,0.0014668913505897774,309.9460916442049,NaN,NaN
6,0.28784891453197203,339.86522911051213,0.27252410287577,334.85175202156336,0.003910526336560166,315.1212938005391,NaN,NaN
7,0.3100089584163729,335.01347708894883,0.3017088080570497,329.8382749326146,0.01591401498857506,330.00000000000006,NaN,NaN
8,0.3075684805815472,330.00000000000006,0.38575217152802166,314.9595687331537,0.04997651868836156,334.85175202156336,NaN,NaN
9,0.36017609010509366,324.8247978436658,0.4090803613359485,309.9460916442049,0.07467491209307278,340.0269541778976,NaN,NaN
10,0.37296570939213003,319.97304582210245,0.43475115729321645,304.9326145552561,0.26559731326437586,340.0269541778976,NaN,NaN
11,0.3951257532765309,315.1212938005391,0.46276771655097015,300.08086253369277,0.30415244304302014,335.01347708894883,NaN,NaN
12,0.41727948285864236,309.9460916442049,0.48726405228242287,294.9056603773585,0.31342499595490014,330.00000000000006,NaN,NaN
13,NaN,NaN,0.5094240961668238,290.05390835579516,0.40449302072275073,314.9595687331537,NaN,NaN
14,NaN,NaN,NaN,NaN,0.4207933920826541,309.9460916442049,NaN,NaN
15,NaN,NaN,NaN,NaN,0.4616911280106395,304.9326145552561,NaN,NaN
16,NaN,NaN,NaN,NaN,0.46744977169850777,299.9191374663073,NaN,NaN
17,NaN,NaN,NaN,NaN,0.5048367555536261,295.067385444744,NaN,NaN
18,NaN,NaN,NaN,NaN,0.5328501576602352,290.05390835579516,NaN,NaN

In [23]:
data.columns

Index(['WT', 'Unnamed: 1', '-4S+4A', 'Unnamed: 3', '-4A+4S', 'Unnamed: 5',
       'Critical Temperature', 'Unnamed: 7'],
      dtype='object')

In [25]:
new_columns = []
last_column_name = None
for column in data.columns:
    if column.startswith("Unnamed"):
        new_columns.append(last_column_name+"_Y")
    else:
        last_column_name = column
        new_columns.append(last_column_name+"_X")

In [26]:
new_columns

['WT_X',
 'WT_Y',
 '-4S+4A_X',
 '-4S+4A_Y',
 '-4A+4S_X',
 '-4A+4S_Y',
 'Critical Temperature_X',
 'Critical Temperature_Y']

In [28]:
data = data.drop(0)
data

,WT_X,WT_Y,-4S+4A_X,-4S+4A_Y,-4A+4S_X,-4A+4S_Y,Critical Temperature_X,Critical Temperature_Y
1,0.004005240870900095,319.97304582210245,0.0003966171125484863,315.1212938005391,0.0010754046086513813,289.89218328840974,0.149717237650606,344.07008086253376
2,0.012302234079078739,324.9865229110512,0.024113136511269034,330.00000000000006,0.000005130370610062496,295.067385444744,0.15663771295971077,338.5714285714286
3,0.04060609409099697,334.85175202156336,0.07223127710710239,334.85175202156336,0.00010300205609467539,300.08086253369277,0.15548535279190814,339.5417789757413
4,0.012400105764563352,330.00000000000006,0.0957552102859984,339.86522911051213,0.00019771659043460454,304.9326145552561,NaN,NaN
5,0.05944481497121068,339.86522911051213,0.25856633766520776,339.86522911051213,0.0014668913505897774,309.9460916442049,NaN,NaN
6,0.28784891453197203,339.86522911051213,0.27252410287577,334.85175202156336,0.003910526336560166,315.1212938005391,NaN,NaN
7,0.3100089584163729,335.01347708894883,0.3017088080570497,329.8382749326146,0.01591401498857506,330.00000000000006,NaN,NaN
8,0.3075684805815472,330.00000000000006,0.38575217152802166,314.9595687331537,0.04997651868836156,334.85175202156336,NaN,NaN
9,0.36017609010509366,324.8247978436658,0.4090803613359485,309.9460916442049,0.07467491209307278,340.0269541778976,NaN,NaN
10,0.37296570939213003,319.97304582210245,0.43475115729321645,304.9326145552561,0.26559731326437586,340.0269541778976,NaN,NaN
11,0.3951257532765309,315.1212938005391,0.46276771655097015,300.08086253369277,0.30415244304302014,335.01347708894883,NaN,NaN
12,0.41727948285864236,309.9460916442049,0.48726405228242287,294.9056603773585,0.31342499595490014,330.00000000000006,NaN,NaN
13,NaN,NaN,0.5094240961668238,290.05390835579516,0.40449302072275073,314.9595687331537,NaN,NaN
14,NaN,NaN,NaN,NaN,0.4207933920826541,309.9460916442049,NaN,NaN
15,NaN,NaN,NaN,NaN,0.4616911280106395,304.9326145552561,NaN,NaN
16,NaN,NaN,NaN,NaN,0.46744977169850777,299.9191374663073,NaN,NaN
17,NaN,NaN,NaN,NaN,0.5048367555536261,295.067385444744,NaN,NaN
18,NaN,NaN,NaN,NaN,0.5328501576602352,290.05390835579516,NaN,NaN

In [51]:
gene_data = {}
buf_column = ""
for column in data.columns:
    if column.endswith("X"):
        if buf_column:
            gene_data[(column, buf_column)] = []
            buf_column = ""
        else:
            buf_column = column
    elif column.endswith("Y"):
        if buf_column:
            gene_data[(buf_column, column)] = []
            buf_column = ""
        else:
             buf_column = column

In [33]:
gene_data

{('WT_X', 'WT_Y'): [],
 ('-4S+4A_X', '-4S+4A_Y'): [],
 ('-4A+4S_X', '-4A+4S_Y'): [],
 ('Critical Temperature_X', 'Critical Temperature_Y'): []}

In [49]:
for v in zip(data["WT_X"], data["WT_Y"]):
    print(v)

('0.004005240870900095', '319.97304582210245')
('0.012302234079078739', '324.9865229110512')
('0.04060609409099697', '334.85175202156336')
('0.012400105764563352', '330.00000000000006')
('0.05944481497121068', '339.86522911051213')
('0.28784891453197203', '339.86522911051213')
('0.3100089584163729', '335.01347708894883')
('0.3075684805815472', '330.00000000000006')
('0.36017609010509366', '324.8247978436658')
('0.37296570939213003', '319.97304582210245')
('0.3951257532765309', '315.1212938005391')
('0.41727948285864236', '309.9460916442049')
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)

In [52]:
for gene_name in gene_data:
    #print(gene_name)
    for v in zip(data[gene_name[0]], data[gene_name[1]]):
        print(v)
        if not pd.isna(v[0]) and not pd.isna(v[1]):
            gene_data[gene_name].append(v)
gene_data

('0.004005240870900095', '319.97304582210245')
('0.012302234079078739', '324.9865229110512')
('0.04060609409099697', '334.85175202156336')
('0.012400105764563352', '330.00000000000006')
('0.05944481497121068', '339.86522911051213')
('0.28784891453197203', '339.86522911051213')
('0.3100089584163729', '335.01347708894883')
('0.3075684805815472', '330.00000000000006')
('0.36017609010509366', '324.8247978436658')
('0.37296570939213003', '319.97304582210245')
('0.3951257532765309', '315.1212938005391')
('0.41727948285864236', '309.9460916442049')
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
('0.0003966171125484863', '315.1212938005391')
('0.024113136511269034', '330.00000000000006')
('0.07223127710710239', '334.85175202156336')
('0.0957552102859984', '339.86522911051213')
('0.25856633766520776', '339.86522911051213')
('0.27252410287577', '334.85175202156336')
('0.3017088080570497', '329.8382749326146')
('0.38575217152802166', '314.9595687331537')
('0.4090803613359485', '309.9460916442049')
('0.43475115729321645', '304.9326145552561')
('0.46276771655097015', '300.08086253369277')
('0.48726405228242287', '294.9056603773585')
('0.5094240961668238', '290.05390835579516')
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
('0.0010754046086513813', '289.89218328840974')
('0.000005130370610062496', '295.067385444744')
('0.00010300205609467539', '300.08086253369277')
('0.00019771659043460454', '304.9326145552561')
('0.0014668913505897774', '309.9460916442049')
('0.003910526336560166', '315.1212938005391')
('0.01591401498857506', '330.00000000000006')
('0.04997651868836156', '334.85175202156336')
('0.07467491209307278', '340.0269541778976')
('0.26559731326437586', '340.0269541778976')
('0.30415244304302014', '335.01347708894883')
('0.31342499595490014', '330.00000000000006')
('0.40449302072275073', '314.9595687331537')
('0.4207933920826541', '309.9460916442049')
('0.4616911280106395', '304.9326145552561')
('0.46744977169850777', '299.9191374663073')
('0.5048367555536261', '295.067385444744')
('0.5328501576602352', '290.05390835579516')
('0.149717237650606', '344.07008086253376')
('0.15663771295971077', '338.5714285714286')
('0.15548535279190814', '339.5417789757413')
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)

{('WT_X', 'WT_Y'): [('0.004005240870900095', '319.97304582210245'),
  ('0.012302234079078739', '324.9865229110512'),
  ('0.04060609409099697', '334.85175202156336'),
  ('0.012400105764563352', '330.00000000000006'),
  ('0.05944481497121068', '339.86522911051213'),
  ('0.28784891453197203', '339.86522911051213'),
  ('0.3100089584163729', '335.01347708894883'),
  ('0.3075684805815472', '330.00000000000006'),
  ('0.36017609010509366', '324.8247978436658'),
  ('0.37296570939213003', '319.97304582210245'),
  ('0.3951257532765309', '315.1212938005391'),
  ('0.41727948285864236', '309.9460916442049')],
 ('-4S+4A_X', '-4S+4A_Y'): [('0.0003966171125484863', '315.1212938005391'),
  ('0.024113136511269034', '330.00000000000006'),
  ('0.07223127710710239', '334.85175202156336'),
  ('0.0957552102859984', '339.86522911051213'),
  ('0.25856633766520776', '339.86522911051213'),
  ('0.27252410287577', '334.85175202156336'),
  ('0.3017088080570497', '329.8382749326146'),
  ('0.38575217152802166', '314.9595687331537'),
  ('0.4090803613359485', '309.9460916442049'),
  ('0.43475115729321645', '304.9326145552561'),
  ('0.46276771655097015', '300.08086253369277'),
  ('0.48726405228242287', '294.9056603773585'),
  ('0.5094240961668238', '290.05390835579516')],
 ('-4A+4S_X', '-4A+4S_Y'): [('0.0010754046086513813', '289.89218328840974'),
  ('0.000005130370610062496', '295.067385444744'),
  ('0.00010300205609467539', '300.08086253369277'),
  ('0.00019771659043460454', '304.9326145552561'),
  ('0.0014668913505897774', '309.9460916442049'),
  ('0.003910526336560166', '315.1212938005391'),
  ('0.01591401498857506', '330.00000000000006'),
  ('0.04997651868836156', '334.85175202156336'),
  ('0.07467491209307278', '340.0269541778976'),
  ('0.26559731326437586', '340.0269541778976'),
  ('0.30415244304302014', '335.01347708894883'),
  ('0.31342499595490014', '330.00000000000006'),
  ('0.40449302072275073', '314.9595687331537'),
  ('0.4207933920826541', '309.9460916442049'),
  ('0.4616911280106395', '304.9326145552561'),
  ('0.46744977169850777', '299.9191374663073'),
  ('0.5048367555536261', '295.067385444744'),
  ('0.5328501576602352', '290.05390835579516')],
 ('Critical Temperature_X',
  'Critical Temperature_Y'): [('0.149717237650606',
   '344.07008086253376'), ('0.15663771295971077', '338.5714285714286'), ('0.15548535279190814',
   '339.5417789757413')]}

In [53]:
for k, v in gene_data.items():
    gene_data[k] = sorted(v)

In [54]:
gene_data

{('WT_X', 'WT_Y'): [('0.004005240870900095', '319.97304582210245'),
  ('0.012302234079078739', '324.9865229110512'),
  ('0.012400105764563352', '330.00000000000006'),
  ('0.04060609409099697', '334.85175202156336'),
  ('0.05944481497121068', '339.86522911051213'),
  ('0.28784891453197203', '339.86522911051213'),
  ('0.3075684805815472', '330.00000000000006'),
  ('0.3100089584163729', '335.01347708894883'),
  ('0.36017609010509366', '324.8247978436658'),
  ('0.37296570939213003', '319.97304582210245'),
  ('0.3951257532765309', '315.1212938005391'),
  ('0.41727948285864236', '309.9460916442049')],
 ('-4S+4A_X', '-4S+4A_Y'): [('0.0003966171125484863', '315.1212938005391'),
  ('0.024113136511269034', '330.00000000000006'),
  ('0.07223127710710239', '334.85175202156336'),
  ('0.0957552102859984', '339.86522911051213'),
  ('0.25856633766520776', '339.86522911051213'),
  ('0.27252410287577', '334.85175202156336'),
  ('0.3017088080570497', '329.8382749326146'),
  ('0.38575217152802166', '314.9595687331537'),
  ('0.4090803613359485', '309.9460916442049'),
  ('0.43475115729321645', '304.9326145552561'),
  ('0.46276771655097015', '300.08086253369277'),
  ('0.48726405228242287', '294.9056603773585'),
  ('0.5094240961668238', '290.05390835579516')],
 ('-4A+4S_X', '-4A+4S_Y'): [('0.000005130370610062496', '295.067385444744'),
  ('0.00010300205609467539', '300.08086253369277'),
  ('0.00019771659043460454', '304.9326145552561'),
  ('0.0010754046086513813', '289.89218328840974'),
  ('0.0014668913505897774', '309.9460916442049'),
  ('0.003910526336560166', '315.1212938005391'),
  ('0.01591401498857506', '330.00000000000006'),
  ('0.04997651868836156', '334.85175202156336'),
  ('0.07467491209307278', '340.0269541778976'),
  ('0.26559731326437586', '340.0269541778976'),
  ('0.30415244304302014', '335.01347708894883'),
  ('0.31342499595490014', '330.00000000000006'),
  ('0.40449302072275073', '314.9595687331537'),
  ('0.4207933920826541', '309.9460916442049'),
  ('0.4616911280106395', '304.9326145552561'),
  ('0.46744977169850777', '299.9191374663073'),
  ('0.5048367555536261', '295.067385444744'),
  ('0.5328501576602352', '290.05390835579516')],
 ('Critical Temperature_X',
  'Critical Temperature_Y'): [('0.149717237650606',
   '344.07008086253376'), ('0.15548535279190814', '339.5417789757413'), ('0.15663771295971077',
   '338.5714285714286')]}

In [36]:
for v in zip(data["WT_X"], data["WT_Y"]):
    print(v)

('0.004005240870900095', '319.97304582210245')
('0.012302234079078739', '324.9865229110512')
('0.04060609409099697', '334.85175202156336')
('0.012400105764563352', '330.00000000000006')
('0.05944481497121068', '339.86522911051213')
('0.28784891453197203', '339.86522911051213')
('0.3100089584163729', '335.01347708894883')
('0.3075684805815472', '330.00000000000006')
('0.36017609010509366', '324.8247978436658')
('0.37296570939213003', '319.97304582210245')
('0.3951257532765309', '315.1212938005391')
('0.41727948285864236', '309.9460916442049')
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)
(nan, nan)

In [21]:
sorted(data["WT_X"])

TypeError: '<' not supported between instances of 'float' and 'str'